export type assetInfo = {
	price: number
}

return {
	[""] = {
		price = math.huge
	},
	["Asset.Chair"] = {
		price = 25
	},
	["Asset.Drawer"] = {
		price = 50
	},
	["Asset.Table"] = {
		price = 50
	},
	["Asset.Checkout"] = {
		price = 100
	},
	["Wall_Outer.Plaster"] = {
		price = 20
	},
	["Wall_Outer.Plaster.Trim"] = {
		price = 30
	},
	["Wall_Outer.Brick"] = {
		price = 15
	},
	["Wall_Inner.DoorSingle"] = {
		price = 150
	},
	["Wall_Inner.Painting"] = {
		price = 80
	},
	["Wall_Inner.Window"] = {
		price = 100
	},
	["Floor"] = {
		price = 15
	},
	["Floor.Carpet"] = {
		price = 25
	},
	["Floor.Concrete"] = {
		price = 20
	},
	["Floor.Grass"] = {
		price = 10
	},
	["Floor.Marble"] = {
		price = 75
	},
	["Floor.Wood"] = {
		price = 20
	}
}